const common = {
	GAME_SPEED: 1,
	GROUND_SCALE: 1,
	GROUND_SUBDIVISIONS_U: 40,
    GROUND_SUBDIVISIONS_V: 40,
    GROUND_Y_SCALE: 1,
    UNIT_SCALE: 1,
	BUILDING_SCALE: 1,
	SPAWNPOINT_SCALE: 1,
    UNIT_SPEED_SCALE: .005,
	FORMATION_SPACING_SCALE: 1.5
}